// Glossary for the animation: the notes' bold terms plus those the film needs. Definitions paraphrase
// course_material/notes/2_prokaryotic_transcription.qmd; `notes` is the section id in notes.html and
// `show` says where to jump (time, optional route, optional molecule to spotlight; `coupling` turns on the ribosome).
export const GLOSSARY=[
  {term:'Abortive initiation',def:'RNAP makes and releases short RNAs while it is still bound to the promoter, before it escapes.',notes:'initiation',show:{t:56}},
  {term:'Active site',aliases:['active centre'],def:'Where RNAP joins nucleotides: a catalytic Mg²⁺ held by β′, between the β and β′ subunits.',notes:'the-mechanism-of-nucleotide-addition',show:{t:108,key:'mg'}},
  {term:'Backtracking',aliases:['backtracks','backtrack'],def:'RNAP slides backwards along the DNA and RNA, so the RNA 3′ end leaves the active site and enters the secondary channel.',notes:'elongation',show:{t:121.8}},
  {term:'Bridge helix',def:'A long β′ helix that spans the active-site cleft; with the trigger loop it helps each step forward.',notes:'the-mechanism-of-nucleotide-addition',show:{t:109,key:'bridgeHelix'}},
  {term:'Closed complex',def:'The holoenzyme bound at a promoter with the DNA still fully double stranded.',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',show:{t:34}},
  {term:'Coding strand',aliases:['non-template strand','non-template (coding) strand','nontemplate strand'],def:'The DNA strand with the same sequence as the RNA (T in place of U). Promoter sequences are written on it.',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',show:{t:47,key:'coding'}},
  {term:'Core enzyme',def:'RNA polymerase without σ (α₂ββ′ω). It can make RNA on a DNA template but cannot recognise promoters.',notes:'bacterial-rna-polymerase-consists-of-multiple-subunits',show:{t:6,key:'rnap'}},
  {term:'Coupled transcription–translation',aliases:['coupling'],def:'In bacteria a ribosome can translate an mRNA while RNAP is still making it; NusG can link the two machines.',notes:'elongation-factors-nusa-and-nusg',show:{t:96,coupling:true}},
  {term:'Elongation',def:'The stage in which RNAP moves along the template, unwinding DNA ahead and rewinding it behind while extending the RNA.',notes:'elongation',show:{t:92}},
  {term:'Exit channel',aliases:['RNA exit channel'],def:'The channel through which the RNA leaves RNAP, beside NusA; hairpins can fold here.',notes:'the-beta-and-beta-subunits',show:{t:130.4}},
  {term:'Hairpin',aliases:['stem–loop','RNA hairpin'],def:'An RNA segment that folds back on itself where two stretches are complementary, forming a paired stem and a loop.',notes:'intrinsic-terminators',show:{t:131,key:'hairpin'}},
  {term:'Holoenzyme',def:'The complete enzyme that starts transcription at promoters: core RNAP plus a σ factor (α₂ββ′ωσ).',notes:'sigma-factors',show:{t:14.6}},
  {term:'Hopping',def:'A proposed search mechanism: RNAP lets go of the DNA briefly and rebinds a short distance away.',notes:'how-does-rnap-find-the-promoter',show:{t:21.5}},
  {term:'Hybrid',aliases:['RNA–DNA hybrid','heteroduplex'],def:'The newest ~8–9 nucleotides of RNA, base paired with the template strand inside RNAP.',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',show:{t:110}},
  {term:'Initiation',def:'The first stage: RNAP finds a promoter, opens the DNA and starts the RNA, until it escapes the promoter.',notes:'initiation',show:{t:15}},
  {term:'Intersegment transfer',aliases:['transfer between nearby DNA segments'],def:'A proposed search mechanism: RNAP moves directly from one DNA segment to another where the two pass close together.',notes:'how-does-rnap-find-the-promoter',show:{t:23.5}},
  {term:'Intrinsic terminator',aliases:['intrinsic termination'],def:'A terminator that needs no protein: a GC-rich hairpin in the RNA followed by a U-rich tract.',notes:'intrinsic-terminators',show:{t:136,path:'intrinsic'}},
  {term:'NusA',def:'An elongation factor bound beside the RNA exit channel. It enhances pausing at RNA hairpins and helps intrinsic termination.',notes:'elongation-factors-nusa-and-nusg',show:{t:84,key:'nusA'}},
  {term:'NusG',def:'An elongation factor that reduces pausing, raising the overall rate. Its KOW domain can link RNAP to the ribosome or to Rho.',notes:'elongation-factors-nusa-and-nusg',show:{t:86,key:'nusG'}},
  {term:'Open complex',def:'The complex in which the DNA has been melted around the start site, exposing the template strand.',notes:'initiation',show:{t:44}},
  {term:'Pausing',aliases:['pause','pauses'],def:'RNAP stopping temporarily. Hairpins and NusA lengthen pauses; NusG shortens them. Pauses give Rho time to catch up.',notes:'elongation-factors-nusa-and-nusg',show:{t:129.5}},
  {term:'Phosphodiester bond',def:'The bond that joins nucleotides: the RNA 3′–OH attacks the incoming NTP’s α phosphate.',notes:'the-mechanism-of-nucleotide-addition',show:{t:111}},
  {term:'Promoter',aliases:['promoters'],def:'The DNA region at the start of a gene, recognised through σ, where RNAP binds and starts transcription. It includes the start point (+1), the first base pair transcribed.',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',show:{t:27.4}},
  {term:'Promoter escape',aliases:['promoter clearance','clears the promoter'],def:'RNAP leaves the promoter once the RNA is about 10–12 nucleotides long; σ is often released soon after.',notes:'the-sigma-cycle',show:{t:72}},
  {term:'Proofreading',def:'Removal of a wrongly added nucleotide: RNAP backtracks and its active site cuts off the RNA end carrying the error.',notes:'elongation',show:{t:121}},
  {term:'Pyrophosphate',aliases:['PPi'],def:'The β and γ phosphates released when a nucleotide is added to the RNA.',notes:'the-mechanism-of-nucleotide-addition',show:{t:111.4,key:'ppi'}},
  {term:'Rho factor',aliases:['Rho'],def:'A ring of six subunits that binds the rut site and uses ATP to move 5′ → 3′ along the RNA until it ends transcription.',notes:'rho-dependent-terminators',show:{t:136,path:'rho',key:'rho'}},
  {term:'Rudder',def:'A β′ element that contacts the RNA at the upstream edge of the hybrid and stabilises the elongation complex.',notes:'the-mechanism-of-nucleotide-addition',show:{t:109}},
  {term:'rut site',aliases:['rut'],def:'Rho utilisation site: an exposed, unstructured stretch of RNA where Rho loads, upstream of the termination point.',notes:'rho-dependent-terminators',show:{t:136,path:'rho'}},
  {term:'Scrunching',def:'During initiation RNAP stays on the promoter and pulls downstream DNA into itself as the RNA grows.',notes:'initiation',show:{t:60}},
  {term:'Secondary channel',aliases:['pore'],def:'A pore in RNAP through which NTPs are thought to reach the active site; a backtracked RNA end also enters it.',notes:'the-beta-and-beta-subunits',show:{t:109}},
  {term:'Sigma factor',aliases:['σ factor','σ70','sigma'],def:'The subunit that gives RNAP promoter specificity: σ70 region 4 reads −35 and region 2 reads −10.',notes:'sigma-factors',show:{t:34,key:'sigma'}},
  {term:'Sigma cycle',aliases:['σ cycle'],def:'σ joins core to start transcription, is often (not always) released after promoter escape, and once released can bind another core enzyme.',notes:'the-sigma-cycle',show:{t:78}},
  {term:'Sliding',def:'A proposed search mechanism: one-dimensional diffusion of RNAP along the DNA.',notes:'how-does-rnap-find-the-promoter',show:{t:18}},
  {term:'Template strand',def:'The DNA strand RNAP reads, 3′ → 5′; each RNA nucleotide pairs with a base on it.',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',show:{t:47,key:'template'}},
  {term:'Termination',def:'The final stage: the RNA–DNA hybrid is broken, the RNA is released and the DNA duplex re-forms.',notes:'transcription-termination',show:{t:136}},
  {term:'Terminator',aliases:['terminators'],def:'The DNA sequence where transcription ends. A transcription unit runs from the promoter to the terminator.',notes:'transcription-termination',show:{t:155.6,path:'rho',routes:{rho:155.6,intrinsic:137.6}}},
  {term:'Translocation',aliases:['translocates'],def:'After each nucleotide is added, RNAP moves one base pair downstream so the next template base enters the active site.',notes:'the-mechanism-of-nucleotide-addition',show:{t:112}},
  {term:'Transcription bubble',aliases:['bubble'],def:'The ~12–14 bp region inside RNAP where the two DNA strands are held apart.',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',show:{t:47}},
  {term:'Trigger loop',def:'A flexible β′ element that folds over a correctly paired NTP for catalysis, then opens again.',notes:'the-mechanism-of-nucleotide-addition',show:{t:110.4,key:'triggerLoop'}},
  {term:'U-rich tract',aliases:['U tract','U-rich'],def:'A run of uridines after an intrinsic terminator hairpin; its weak rU·dA pairs let the hybrid come apart.',notes:'intrinsic-terminators',show:{t:150,path:'intrinsic',key:'utract'}},
  {term:'−10 element',aliases:['−10'],def:'Promoter hexamer (consensus TATAAT) about 10 bp upstream of the start site, read by σ region 2; the DNA melts here.',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',show:{t:27.4,key:'promoter10'}},
  {term:'−35 element',aliases:['−35'],def:'Promoter hexamer (consensus TTGACA) about 35 bp upstream of the start site, read by σ region 4.',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',show:{t:27.4,key:'promoter35'}}
];
export const glossarySlug=term=>term.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
