// What the inspector and the 'Find a molecule' toolbar say about each molecule. Wording follows the
// lecture notes (course_material/notes/2_prokaryotic_transcription.qmd); `notes` is the section id in
// notes.html and `at` lists [chapter name, time] jumps. Genes are E. coli.
export const INFO={
  alphaI:{short:'Assembly scaffold',title:'α subunit (αI)',gene:'rpoA',color:'#d6c496',notes:'the-alpha-subunits',at:[['Core enzyme',0]],
    text:'Two α subunits form a dimer, the scaffold on which the core enzyme assembles. Their flexible C-terminal domains (not resolved in 8E6X, and not shown) can contact promoter DNA.'},
  alphaII:{short:'Assembly scaffold',title:'α subunit (αII)',gene:'rpoA',color:'#d6c496',notes:'the-alpha-subunits',at:[['Core enzyme',0]],
    text:'The second α subunit of the α₂ scaffold. Together the α dimer holds β and β′ in place.'},
  beta:{short:'Catalytic subunit · forms the channels',title:'β subunit',gene:'rpoB',color:'#56c2b1',notes:'the-beta-and-beta-subunits',at:[['Core enzyme',2.5],['Nucleotide addition',108]],
    text:'One of the two large catalytic subunits. With β′ it forms the active centre, the main DNA channel, the secondary channel for NTPs and the RNA exit channel.'},
  betaPrime:{short:'Catalytic subunit · holds the Mg²⁺',title:'β′ subunit',gene:'rpoC',color:'#7fa3e3',notes:'the-beta-and-beta-subunits',at:[['Core enzyme',5],['Nucleotide addition',108]],
    text:'The largest subunit. It carries the NADFDGD motif that holds the catalytic Mg²⁺, the bridge helix and the trigger loop, and lines the secondary channel.'},
  omega:{short:'Small subunit · not essential',title:'ω subunit',gene:'rpoZ',color:'#c2bdb2',notes:'bacterial-rna-polymerase-consists-of-multiple-subunits',at:[['Core enzyme',5.5]],
    text:'A small subunit bound to β′. Its function is not fully understood and it is not essential for transcription.'},
  sigma:{short:'Promoter recognition · reads −35 and −10',title:'σ70 factor',gene:'rpoD',color:'#f094ae',notes:'sigma-factors',at:[['Sigma binding',9],['Closed complex',34],['Promoter escape',72]],
    text:'Gives the core enzyme promoter specificity: region 4 reads the −35 element and region 2 the −10 element, which it helps to melt. It is often released after promoter escape and can then be reused.'},
  nusA:{short:'Enhances pausing at RNA hairpins',title:'NusA',gene:'nusA',color:'#b9d56b',notes:'elongation-factors-nusa-and-nusg',at:[['Elongation factors',84],['Hairpin pause',129.5]],
    text:'An elongation factor bound beside the RNA exit channel. It enhances pausing at RNA hairpins, which also helps intrinsic termination.'},
  nusG:{short:'Reduces pausing · can bridge to Rho',title:'NusG',gene:'nusG',color:'#c08a4c',notes:'elongation-factors-nusa-and-nusg',at:[['Elongation factors',86],['Rho engagement',180,'rho']],
    text:'An elongation factor bound across the DNA channel. It reduces pausing, raising the overall rate, and can link RNAP to the ribosome or to Rho.'},
  ribosome:{short:'Translates the RNA as it is made (schematic)',title:'Ribosome (70S, schematic)',color:'#e3d6b8',notes:'elongation-factors-nusa-and-nusg',at:[['Elongation',96]],
    text:'A schematic 70S ribosome: a small 30S and a large 50S lobe, not a structure. It binds the ribosome-binding site, translates from AUG and stops at UAA while RNAP is still transcribing; NusG’s KOW domain can link the two (coupling). Shown only with Coupled translation on.'},
  rho:{short:'Hexameric RNA translocase',title:'Rho factor',gene:'rho',color:'#9d7cc0',notes:'rho-dependent-terminators',at:[['Rho loading',136,'rho'],['Rho traversal',146,'rho']],
    text:'A ring of six identical subunits. It binds the rut site on the RNA and uses its ATPase to move 5′ → 3′ along the transcript until it reaches RNAP and ends transcription.'},
  template:{short:'Read 3′ → 5′',title:'Template strand',color:'#72cdeb',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',at:[['Open complex',44]],
    text:'The DNA strand that RNAP reads, 3′ → 5′. Each RNA nucleotide pairs with a base on this strand.'},
  coding:{short:'Same sequence as the RNA',title:'Coding (non-template) strand',color:'#e9e1cf',notes:'transcription-occurs-by-base-pairing-in-a-bubble-of-unpaired-dna',at:[['Open complex',44]],
    text:'The strand with the same sequence as the RNA (T in place of U). Promoter sequences are written on this strand.'},
  rna:{short:'Made 5′ → 3′',title:'RNA transcript',color:'#ffa45e',notes:'the-mechanism-of-nucleotide-addition',at:[['Abortive initiation',56],['Elongation',92]],
    text:'Made 5′ → 3′. The newest ~9 nucleotides pair with the template in the RNA–DNA hybrid; older RNA leaves through the exit channel.'},
  ntp:{short:'Base, ribose and α, β, γ phosphates',title:'Incoming NTP',color:'#ffa45e',notes:'the-mechanism-of-nucleotide-addition',at:[['Nucleotide addition',108]],
    text:'A ribonucleoside triphosphate: base, ribose and α, β, γ phosphates. The RNA 3′–OH attacks its α phosphate; β and γ leave as pyrophosphate.'},
  ppi:{short:'The β and γ phosphates, released',title:'Pyrophosphate (PPi)',color:'#f2c46d',notes:'the-mechanism-of-nucleotide-addition',at:[['Nucleotide addition',108]],
    text:'The β and γ phosphates that leave when a nucleotide is added. Cleaving them off provides the energy for the new phosphodiester bond.'},
  mg:{short:'Catalytic metal ion',title:'Active-site Mg²⁺',color:'#c8ffd8',notes:'the-mechanism-of-nucleotide-addition',at:[['Nucleotide addition',108],['Proofreading',121]],
    text:'Held by β′ aspartates (NADFDGD). It catalyses phosphodiester-bond formation and, after backtracking, the cleavage that removes an error.'},
  bridgeHelix:{short:'Spans the active-site cleft',title:'Bridge helix',gene:'rpoC',color:'#bfeaf2',notes:'the-mechanism-of-nucleotide-addition',at:[['Nucleotide addition',108]],
    text:'A long β′ helix spanning the cleft beside the active site. With the trigger loop it helps each translocation step.'},
  triggerLoop:{short:'Folds over the NTP (schematic)',title:'Trigger loop',gene:'rpoC',color:'#f3e3c2',notes:'the-mechanism-of-nucleotide-addition',at:[['Nucleotide addition',108]],
    text:'A flexible β′ element that folds over a correctly paired NTP, closing the active site for catalysis, then opens again. Its tip is unresolved in 8E6X, so this fold is schematic.'},
  promoter35:{short:'TTGACA · read by σ region 4',title:'−35 element',color:'#f0a0b4',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',at:[['The promoter',27.4],['Closed complex',34]],
    text:'Consensus TTGACA on the coding strand, read by σ region 4.'},
  promoter10:{short:'TATAAT · read by σ region 2',title:'−10 element',color:'#f0a0b4',notes:'sigma-factors-control-binding-to-dna-by-recognising-promoter-sequences',at:[['The promoter',27.4],['Closed complex',34],['Open complex',44]],
    text:'Consensus TATAAT, 16–18 bp downstream of −35. σ region 2 reads it and the DNA melts here.'},
  start:{short:'First transcribed base pair',title:'+1 start site',color:'#dcefff',notes:'initiation',at:[['The promoter',27.4],['Open complex',44]],
    text:'The first transcribed base pair. Positions upstream are negative and downstream positive; there is no position 0.'},
  hairpin:{short:'RNA stem–loop',title:'RNA hairpin',color:'#ffd88f',notes:'intrinsic-terminators',at:[['Hairpin pause',129.5],['Hairpin formation',142,'intrinsic']],
    text:'Complementary RNA segments pair into a stem–loop. A GC-rich hairpin followed by a U tract is an intrinsic terminator.'},
  utract:{short:'Weak rU·dA pairs',title:'U-rich tract',color:'#ffe1a0',notes:'intrinsic-terminators',at:[['Intrinsic terminator',136,'intrinsic']],
    text:'Uridines paired with template adenines: weak rU·dA pairs that let the hybrid come apart after the hairpin forms.'},
  error:{short:'C opposite template A · stalls RNAP',title:'Misincorporated nucleotide',color:'#ff6f88',notes:'elongation',at:[['Nucleotide addition',117],['Proofreading',121]],
    text:'A C added opposite a template A. The mismatch stalls RNAP, which backtracks and cuts it off with the adjacent nucleotide.'}
};
// Subunit chain letters in 8E6X.
export const CHAIN_KEY={C:'alphaI',D:'alphaII',A:'beta',B:'betaPrime',E:'omega',F:'nusG'};
