// Protein browser content: groups, then one entry per protein in display order. `notes` is the
// section id in notes.html; `related` lists other entry ids; `table` holds the σ factor table row.
export const GROUPS=[
  {id:'rnap',title:'RNA polymerase',
    intro:'In bacteria a single type of RNA polymerase makes rRNA, mRNA and tRNA, and it is built from five types of subunit.'},
  {id:'sigma',title:'Sigma factors',
    intro:'σ factors join the core enzyme to form the holoenzyme and direct it to specific promoters; E. coli has seven.'},
  {id:'factors',title:'Elongation and termination factors',
    intro:'Elongation factors bind the elongating RNA polymerase and influence its speed and pausing; Rho factor binds the transcript and ends transcription at rho-dependent terminators.'}
];

export const PROTEINS=[
  {id:'core',group:'rnap',name:'Core enzyme',symbol:'α₂ββ′ω',gene:null,
    short:'RNA polymerase without σ · makes RNA',
    notes:'bacterial-rna-polymerase-consists-of-multiple-subunits',
    related:['holoenzyme','beta','betaPrime','alpha','omega','sigma70'],
    facts:[
      'The core enzyme is RNA polymerase without σ: two α subunits, β, β′ and ω (α₂ββ′ω).',
      'It can synthesise RNA on a DNA template, but alone it cannot recognise promoters.',
      'It binds indiscriminately to any DNA, mainly through electrostatic interactions between the basic protein and the acidic DNA. When bound in this way, the DNA remains in duplex form.',
      'Viewed from its upstream face, the enzyme has a “crab claw” shape.',
      'It reads the template strand 3′ → 5′, so the RNA chain grows 5′ → 3′: the 3′–OH of the last nucleotide reacts with the 5′-triphosphate of the incoming one. RNA polymerase performs the base pairing and nucleotide addition by itself, and both catalyses and monitors the process.',
      'During elongation it carries the transcription bubble along the DNA, unwinding the duplex at the front (the unwinding point) while the double helix re-forms at the back (the rewinding point). The bubble is about 12 to 14 bp, but the RNA–DNA hybrid within it is only 8 to 9 bp.',
      'As the DNA duplex re-forms behind the enzyme, the RNA is displaced as a free polynucleotide chain. At any moment, the last 14 ribonucleotides of the growing RNA are complexed with the DNA and/or the enzyme.',
      'Elongation is processive: the enzyme disrupts base pairing in the duplex, exposing the template strand for nucleotide addition, and moves downstream with the bubble.',
      'Bacterial RNA polymerase adds 40–50 nucleotides per second, much slower than DNA replication at 800 bp per second.',
      'Inside the enzyme, the DNA template makes a sharp 90° turn at the active site, helped by a “wall” of protein.',
      'The rudder contacts the nascent RNA at the upstream edge of the RNA–DNA hybrid and helps stabilise the elongation complex. It does not melt the incoming DNA duplex.',
      'The bases at the enzyme’s contact points change every time it moves forward one position, so it must keep tight contact with the nucleic acids yet break and remake these contacts with each nucleotide added. Flexible parts of the enzyme fold around each incoming nucleotide for catalysis, then unfold so the enzyme can move to the next position.',
      'During elongation RNA polymerase pauses, and even arrests, at certain sequences. It can backtrack along the template and remove a few nucleotides from the RNA after an error or a displacement of the RNA’s 3′ end.',
      'Termination typically occurs after a long pause or at a terminator sequence: the transcript is released, the bubble closes and the enzyme detaches from the DNA. All the hydrogen bonds holding the RNA–DNA heteroduplex must be broken so that the DNA duplex can re-form.',
      'Long pauses can also end transcription prematurely, by collapsing the bubble and disrupting the RNA–DNA heteroduplex.',
      'At intrinsic terminators it stops without help from any other protein: termination depends only on the RNA product, which folds into a G+C-rich hairpin followed by a run of up to seven uracil residues. The hairpin destabilises the RNA–DNA hybrid, leading to transcript release.'
    ]},
  {id:'holoenzyme',group:'rnap',name:'Holoenzyme',symbol:'α₂ββ′ωσ',gene:null,
    short:'Complete RNA polymerase: core enzyme plus σ',
    notes:'sigma-factors',
    related:['core','sigma70','sigmaS','sigma54'],
    facts:[
      'The holoenzyme is the complete RNA polymerase: the core enzyme plus a σ factor (α₂ββ′ωσ).',
      'In E. coli it weighs approximately 460 kD and is built from five types of subunit: α, β, β′, ω and σ.',
      'The best genetically and biochemically characterised RNA polymerases are those of the bacteria E. coli, Thermus aquaticus and Thermus thermophilus.',
      'It is the form of the enzyme that initiates transcription from promoters; σ allows it to recognise the promoter sequence.',
      'Compared with the core enzyme, its association constant for random DNA is reduced by a factor of 1,000, and its association constant for the promoter is increased by a factor of 1,000.',
      'The rate at which it binds different promoters varies widely. This is an important parameter in determining promoter strength: the efficiency of an individual promoter in initiating transcription.',
      'When bound, RNA polymerase spans approximately 75 bp of DNA, yet there is very little consensus across promoters over that length. Only a few short sequences, such as the −10 and −35 elements, are significantly conserved.',
      'It first binds double-stranded promoter DNA as a closed complex, with no bubble, then locally unwinds the promoter region, including the start point, to form the open complex.',
      'In abortive initiation it stays bound to the promoter and goes through repeated cycles of making and releasing short transcripts, typically 2–10 nucleotides long.',
      'Once the transcript reaches approximately 10–12 nucleotides, it clears the promoter and moves into elongation. Promoter escape weakens σ–core interactions: σ is often released, but some complexes retain it far downstream.',
      'Kinetic measurements of its binding and unbinding rates show that searching the approximately 4.6 million base pairs of the E. coli genome for a promoter through non-specific contacts with random stretches of DNA would be far too slow.',
      'A more likely model: it diffuses through the cell, binds DNA non-specifically and slides randomly along it. Because bacterial DNA is tightly packed into the nucleoid, it can readily move to another nearby piece of DNA by intersegment transfer, repeating the process until it finds a promoter. Hopping, by intradomain association and dissociation, has also been proposed.',
      'These proposed mechanisms may let it search locally along DNA or move between nearby DNA segments; how much each contributes relative to three-dimensional diffusion depends on experimental context.',
      'Each bacterial cell has only approximately 13,000 RNA polymerase molecules at a time.',
      'Where RNA polymerase binds can be mapped by DNA footprinting: the DNA it covers is protected from partial endonuclease digestion, so the corresponding bands are missing when the fragments are separated by polyacrylamide gel electrophoresis.'
    ]},
  {id:'beta',group:'rnap',name:'β subunit',symbol:'β',gene:'rpoB',
    short:'Catalytic subunit · active centre and channels',
    notes:'the-beta-and-beta-subunits',
    related:['betaPrime','core','alpha'],
    facts:[
      'β is one of the two catalytic subunits which, with β′, are responsible for adding nucleotides to the RNA chain.',
      'Together, β and β′ make up most of the mass of the enzyme.',
      'With β′, it forms the active centre, the main channel through which the DNA passes, the secondary channel through which ribonucleotides enter, and the exit channel through which the RNA leaves.',
      'The amino acid sequences and 3D structures of β and β′ are conserved with the largest subunits of the RNA polymerases of bacteria, archaea and eukaryotes. This indicates that the basic features of transcription are shared by all organisms.',
      'Mutations in rpoB and rpoC, the genes encoding β and β′, have been shown to affect all stages of transcription.',
      'At the active centre, the 3′–OH of the last RNA nucleotide attacks an incoming nucleoside 5′–triphosphate. The γ and β phosphates are lost, and the α phosphate forms the phosphodiester bond.',
      'ATP, the energy currency of the cell, is also the substrate for adding adenine to RNA; cleaving two of its phosphate groups provides the energy for the phosphodiester bond. In DNA synthesis, dATP is added instead.'
    ]},
  {id:'betaPrime',group:'rnap',name:'β′ subunit',symbol:'β′',gene:'rpoC',
    short:'Catalytic subunit · partner of β',
    notes:'the-beta-and-beta-subunits',
    related:['beta','core','rho'],
    facts:[
      'β′ is one of the two catalytic subunits which, with β, are responsible for adding nucleotides to the RNA chain.',
      'Together, β′ and β account for most of the mass of the enzyme.',
      'With β, it forms the active centre, the main DNA channel, the secondary channel for incoming ribonucleotides and the RNA exit channel.',
      'Its amino acid sequence and 3D structure are conserved with the largest RNA polymerase subunits in all domains of life, showing that the basic features of transcription are shared by all organisms.',
      'Mutations in rpoC, like those in rpoB, have been shown to affect all stages of transcription.',
      'Incoming nucleotides are thought to reach the active site through the secondary channel formed by β′ and β, sometimes called a pore.',
      'The RNA leaves through the exit channel. In Rho-dependent termination, Rho invades this channel to release the transcript.'
    ]},
  {id:'alpha',group:'rnap',name:'α subunits (α₂ dimer)',symbol:'α₂',gene:'rpoA',
    short:'Assembly scaffold · contacts the promoter',
    notes:'the-alpha-subunits',
    related:['core','beta','betaPrime','sigma70'],
    facts:[
      'RNA polymerase contains two α subunits, which form a dimer.',
      'The α dimer serves as the scaffold for the assembly of the core enzyme.',
      'The α subunits are responsible for enzyme assembly and promoter recognition.',
      'The C-terminus of each α subunit directly contacts the promoter, and so contributes somewhat to promoter recognition.',
      'The α subunits are part of both the core enzyme (α₂ββ′ω) and the holoenzyme (α₂ββ′ωσ).'
    ]},
  {id:'omega',group:'rnap',name:'ω subunit',symbol:'ω',gene:'rpoZ',
    short:'Function not fully understood · not fully essential',
    notes:'bacterial-rna-polymerase-consists-of-multiple-subunits',
    related:['core','holoenzyme'],
    facts:[
      'RNA polymerase contains one ω subunit, one of its five types of subunit.',
      'ω is part of the core enzyme (α₂ββ′ω), and so of the holoenzyme (α₂ββ′ωσ).',
      'The function of the ω subunit is not yet fully understood.',
      'It is not fully essential for the function of the enzyme.'
    ]},
  {id:'sigma70',group:'sigma',name:'σ70 factor',symbol:'σ70',gene:'rpoD',
    short:'Housekeeping σ factor · transcribes most genes',
    notes:'sigma-factors',
    related:['holoenzyme','core','sigmaS','sigma54','nusA'],
    aka:['Sigma 70','RpoD','primary σ factor'],
    table:{size:'613 amino acids',promoters:'about 1,000',sequence:'TTGACA—16 to 18 bp—TATAAT'},
    facts:[
      'σ70 is the “housekeeping” or primary σ factor (Group 1) and transcribes most genes in growing cells. Every cell has a housekeeping σ factor that keeps essential genes and pathways operating.',
      'With σ38 (σS), the starvation/stress response factor, σ70 is one of the two most important σ factors of E. coli.',
      'Adding σ to the core enzyme forms the holoenzyme (α₂ββ′ωσ), which can both recognise the promoter sequence and initiate transcription.',
      'σ reduces non-specific binding of RNA polymerase to DNA: the association constant for random DNA falls by a factor of 1,000, while that for the promoter rises by a factor of 1,000.',
      'σ70-family factors generally recognise two 6-bp elements upstream of the start site: the −35 element (consensus TTGACA) and the −10 element (TATAAT, sometimes called the TATA box or Pribnow box). Their numbers give their positions relative to the transcription start site. A spacer of 16 to 18 bp separates them; it has no consensus sequence, but 17 bp is the consensus length.',
      'The −35 and −10 elements interact with σ and are usually the most important for promoter recognition, although many other promoter elements also contribute.',
      'Promoter mutations that bring these elements closer to the consensus, or the spacer closer to 17 bp, are likely to be up mutations that strengthen the promoter. Changes away from the consensus are likely to be down mutations.',
      'In the holoenzyme, σ is extended and its domains are connected by flexible linkers.',
      'σ factors are an example of a transcription factor: a protein that modulates the activity of RNA polymerase for specific promoters.',
      'In the sigma cycle, a pool of σ factors competes for binding to the core enzyme. Promoter escape weakens σ–core interactions and σ is often released, although release is not required for elongation and some complexes retain σ far downstream. Released σ can bind another core enzyme and direct a new round of initiation at another promoter.',
      'NusA, binding competitively to the elongating complex, may help to displace σ.',
      'Of the seven σ factors in E. coli, σ70 is the largest (613 amino acids) and directs RNA polymerase to the most promoters, about 1,000.'
    ]},
  {id:'sigmaS',group:'sigma',name:'σS factor',symbol:'σS',gene:'rpoS',
    short:'Starvation and stress-response σ factor',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigma70','holoenzyme','sigma32'],
    aka:['σ38','Sigma 38','Sigma S','RpoS'],
    table:{size:'330 amino acids',promoters:'about 100',sequence:'TTGACA—16 to 18 bp—TATAAT'},
    facts:[
      'σS, also known as σ38 or RpoS and encoded by rpoS, is the starvation/stress response σ factor.',
      'With σ70, the housekeeping factor, it is one of the two most important σ factors of E. coli.',
      'When the cell is starved for nutrients or under environmental stress, σ38 holoenzymes bind to their consensus sequence and transcribe the genes required for the stress response and survival.',
      'It recognises the same promoter consensus as σ70: TTGACA—16 to 18 bp—TATAAT.',
      'It is 330 amino acids long and directs RNA polymerase to about 100 promoters.',
      'Specialised σ factors such as σS bind the promoters of genes appropriate to the environmental conditions, increasing the transcription of those genes.',
      'Like any σ factor, it associates with a core enzyme to form a holoenzyme.'
    ]},
  {id:'sigma54',group:'sigma',name:'σ54 factor',symbol:'σ54',gene:'rpoN',
    short:'Recognises distinct −24 and −12 elements',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigma70','holoenzyme','sigmaS'],
    aka:['Sigma 54'],
    table:{size:'477 amino acids',promoters:'about 5',sequence:'TGGCACG—N4—TTGC (−24/−12 elements)'},
    facts:[
      'σ54, encoded by rpoN, is one of the seven σ factors of E. coli, each of which causes RNA polymerase to initiate at a set of promoters defined by specific sequences.',
      'Unlike σ70-family factors, which generally recognise −35 and −10 elements, σ54 recognises distinct −24 and −12 elements.',
      'Its promoter consensus is TGGCACG—N4—TTGC, spanning the −24 and −12 elements.',
      'The σ factors of E. coli control the expression of sets of genes associated with different cellular functions under different environmental conditions.',
      'It is 477 amino acids long and directs RNA polymerase to about 5 promoters.',
      'Like any σ factor, it associates with the core enzyme to form a holoenzyme that can recognise its promoters and initiate transcription.',
      'Differences in protein structure between σ factors are what allow them to bind different promoter sequences.'
    ]},
  {id:'sigma32',group:'sigma',name:'σ32 factor',symbol:'σ32',gene:'rpoH',
    short:'Specialised σ factor · about 30 promoters',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigmaS','sigmaF','sigmaE','sigma70'],
    aka:['Sigma 32'],
    table:{size:'284 amino acids',promoters:'about 30',sequence:'CCCTTGAA—13 to 15 bp—CCCGATNT'},
    facts:[
      'σ32, encoded by rpoH, is one of the seven σ factors of E. coli, each directing RNA polymerase to a set of promoters defined by specific sequences.',
      'It is 284 amino acids long and directs RNA polymerase to about 30 promoters.',
      'Its promoter consensus is CCCTTGAA—13 to 15 bp—CCCGATNT.',
      'Specialised σ factors control the expression of sets of genes associated with different cellular functions under different environmental conditions.',
      'Differences in protein structure between σ factors are what allow them to bind different promoter sequences.',
      'Like any σ factor, it associates with a core enzyme to form a holoenzyme.'
    ]},
  {id:'sigmaF',group:'sigma',name:'σF factor',symbol:'σF',gene:'rpoF',
    short:'Specialised σ factor · about 40 promoters',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigma32','sigmaE','sigma70'],
    aka:['Sigma F'],
    table:{size:'239 amino acids',promoters:'about 40',sequence:'CTAAA—15 bp—GCCGATAA'},
    facts:[
      'σF is one of the seven σ factors of E. coli, encoded by rpoF.',
      'It is 239 amino acids long and directs RNA polymerase to about 40 promoters.',
      'Its promoter consensus is CTAAA—15 bp—GCCGATAA.',
      'Like other specialised σ factors, it binds the promoters of genes appropriate to particular environmental conditions, increasing the transcription of those genes.',
      'Its protein structure differs from that of the other σ factors, which allows it to bind a different promoter sequence.',
      'Like any σ factor, it associates with a core enzyme to form a holoenzyme.'
    ]},
  {id:'sigmaE',group:'sigma',name:'σE factor',symbol:'σE',gene:'rpoE',
    short:'Specialised σ factor · about 20 promoters',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigma32','sigmaF','fecI'],
    aka:['Sigma E'],
    table:{size:'202 amino acids',promoters:'about 20',sequence:'GAA—16 bp—YCTGA'},
    facts:[
      'σE is one of the seven σ factors of E. coli, encoded by rpoE.',
      'It is 202 amino acids long and directs RNA polymerase to about 20 promoters.',
      'Its promoter consensus is GAA—16 bp—YCTGA.',
      'Specialised σ factors such as σE control sets of genes associated with different cellular functions under different environmental conditions.',
      'Differences in protein structure between σ factors are what allow them to bind different promoter sequences.',
      'Like any σ factor, it associates with a core enzyme to form a holoenzyme.'
    ]},
  {id:'fecI',group:'sigma',name:'FecI σ factor',symbol:'FecI',gene:'fecI',
    short:'Smallest σ factor · about 1–2 promoters',
    notes:'different-sigma-factors-bind-to-different-consensus-sequences',
    related:['sigmaE','sigma70','sigma54'],
    aka:['Sigma FecI'],
    table:{size:'173 amino acids',promoters:'about 1–2',sequence:'?'},
    facts:[
      'FecI, encoded by fecI, is one of the seven σ factors of E. coli.',
      'At 173 amino acids, it is the smallest of the seven.',
      'It directs RNA polymerase to only about 1–2 promoters, the fewest of any E. coli σ factor.',
      'Like other specialised σ factors, it causes RNA polymerase to initiate at its own set of promoters, defined by specific sequences.',
      'Specialised σ factors control the expression of sets of genes associated with different cellular functions under different environmental conditions.',
      'Differences in protein structure between σ factors are what allow them to bind different promoter sequences.',
      'Like any σ factor, it associates with a core enzyme to form a holoenzyme.'
    ]},
  {id:'nusA',group:'factors',name:'NusA',symbol:'NusA',gene:'nusA',
    short:'Elongation factor · enhances pausing at hairpins',
    notes:'elongation-factors-nusa-and-nusg',
    related:['nusG','sigma70','core'],
    facts:[
      'NusA is one of the two most important elongation factors in bacteria: accessory proteins that bind the elongating RNA polymerase and influence its speed and pausing behaviour.',
      'NusA primarily enhances transcriptional pausing, especially at sequences that form hairpin structures.',
      'By encouraging RNA polymerase to pause at these sites, NusA plays a crucial role in facilitating intrinsic termination.',
      'NusA is thought to compete with the σ factor for binding to the core enzyme, and may help to displace σ from the elongating complex.',
      'σ release is common, but is not always required for elongation.',
      'Its effect on pausing is opposite to that of NusG, an anti-pausing factor.',
      'Intrinsic terminators need no other protein to stop transcription; termination depends only on the RNA product. A palindromic G+C-rich region of the transcript folds into a hairpin, 7 to 20 bp long, followed by a series of up to seven uracil residues (thymine on the DNA nontemplate strand, adenine on the template strand).',
      'The hairpin destabilises the RNA–DNA hybrid, leading to transcript release. In E. coli, approximately 1,100 sequences in the genome fit this pattern, so approximately half of all terminators are intrinsic.'
    ]},
  {id:'nusG',group:'factors',name:'NusG',symbol:'NusG',gene:'nusG',
    short:'Anti-pausing factor · links RNAP to the ribosome',
    notes:'elongation-factors-nusa-and-nusg',
    related:['nusA','rho','core'],
    facts:[
      'NusG is one of the two most important elongation factors in bacteria, binding the elongating RNA polymerase and influencing its speed and pausing behaviour.',
      'NusG is often considered an anti-pausing factor that increases the overall rate and processivity of transcription.',
      'It physically couples the ribosome to the RNA polymerase complex, directly linking transcription and translation.',
      'It is a key component in Rho-dependent termination, where it helps the Rho factor interact with the paused polymerase.',
      'Its effect contrasts with that of NusA, which enhances pausing.'
    ]},
  {id:'rho',group:'factors',name:'Rho factor',symbol:'Rho',gene:'rho',
    short:'Termination factor · tracks along the RNA to RNAP',
    notes:'rho-dependent-terminators',
    related:['nusG','nusA','core'],
    facts:[
      'Rho factor is the protein needed to stop transcription at rho-dependent terminators, one of the two types of terminator in prokaryotes.',
      'Rho-dependent terminators lack the hairpin structures of intrinsic terminators; they depend on Rho to stop transcription.',
      'Rho first binds to a rho utilisation (rut) site in the transcript, upstream of the termination site.',
      'Because it must travel from the rut site to the point of termination, Rho has to catch up with RNA polymerase during transcription.',
      'It has a C-terminal ATPase domain that allows it to translocate along the RNA, using ATP hydrolysis, until it catches up with RNA polymerase.',
      'Under normal conditions, Rho can translocate faster than RNA polymerase. Even so, pauses by RNA polymerase provide favourable sites and time for efficient rho-dependent termination.',
      'Rho reaches the RNA–DNA hybrid in RNA polymerase. When the polymerase reaches the termination site, Rho freezes its structure, invades the exit channel and destabilises the enzyme, releasing the RNA from the DNA.',
      'NusG helps Rho interact with the paused polymerase.',
      'Termination requires that all the hydrogen bonds holding together the RNA–DNA heteroduplex be broken, allowing the DNA duplex to re-form.'
    ]}
];
